beautify_dict = {
    'psnr': 'PSNR (FR; over YUV)',
    'identity': 'Identity (FR; over YUV)',
    'ssim': 'SSIM (FR; over YUV)',
    'msssim': 'MSSSIM (FR; over YUV)',
    'msssim_fast': 'MSSSIM_fast (FR; over YUV)',
    'msssim_precise': 'MSSSIM_precise (FR; over YUV)',
    'msssim_cuda': 'MSSSIM_cuda (FR; over Y)',
    'msssim OpenCL0': 'MSSSIM OpenCL0 (FR; over YUV)',
    'msssim OpenCL1': 'MSSSIM OpenCL1 (FR; over YUV)',
    '3ssim': '3SSIM (FR; over Y)',
    '3ssim_cuda' : '3SSIM CUDA (FR; over Y)',
    '3ssim OpenCL0': '3SSIM OpenCL0 (FR; over Y)',
    '3ssim OpenCL1': '3SSIM OpenCL1 (FR; over Y)',
    'vqm': 'VQM (FR; over Y)',
    'blocking': 'Blocking (NR; over Y)',
    'blurring': 'Blurring (NR; over Y)',
    'blurring_delta': 'Blurring_delta (NR; over YUV)',
    'msad': 'MSAD (FR; over Y)',
    'mse': 'MSE (FR; over Y)',
    'niqe': 'NIQE (NR; over Y)',
    'niqe OpenCL0': 'NIQE OpenCL0 (NR; over Y)',
    'vmaf': 'VMAF (FR; over Y)',
    'vmaf OpenCL0': 'VMAF OpenCL0 (FR; over Y)',
    'vmaf OpenCL1': 'VMAF OpenCL1 (FR; over Y)',
    'vmaf_legacy': 'VMAF Legacy (FR; over Y)',
    'vmaf_legacy OpenCL0': 'VMAF Legacy OpenCL0 (FR; over Y)',
    'vmaf_legacy OpenCL1': 'VMAF Legacy OpenCL1 (FR; over Y)',
    'bfm': 'BFM (NR; over Y)',
    'bi_psnr': 'BI PSNR (FR; over Y)',
    'ne': 'Noise Estimation (NR; over Y)',
    'psnr_Y': 'PSNR (FR; over Y)',
    'dists': 'DISTS (FR; over RGB)',
    'a-dists': 'A-DISTS (FR; over RGB)',
    'erqa1_0': 'ERQA (ver 1.0) (FR; over RGB)',
    'erqa1_1': 'ERQA (ver 1.1) (FR; over RGB)',
    'erqa2_0': 'ERQA (ver 2.0) (FR; over YUV)',
    'erqa_torch': 'ERQA_torch (FR; over RGB)',
    'mdtvsfa': 'MDTVSFA (NR; over RGB)',
    'lpips_vgg': 'LPIPS (VGG) (FR; over RGB)',
    'lpips_alex': 'LPIPS (Alex) (FR; over RGB)',
    'linearity': 'Linearity (NR; over RGB)',
    'vsfa': 'VSFA (NR; over RGB)',
    'maniqa': 'MANIQA (NR; over RGB)',
    'paq2piq': 'PaQ-2-PiQ (NR; over RGB)',
    'pieapp': 'PieAPP (FR; over RGB)',
    'nima': 'NIMA (NR; over RGB)',
    'ahiq' : 'AHIQ (FR; over RGB)',
    'brisque' : 'BRISQUE (NR; over RGB)',
    'fsim' : 'FSIM (FR; over RGB)',
    'dbcnn' : 'DBCNN (NR; over RGB)',
    'vif' : 'VIF (FR; over RGB)',
    'hyperiqa' : 'HyperIQA (NR; over RGB)',
    'clipiqa' : "ClipIQA (NR; over RGB)",
    'clipiqa+' : "ClipIQA+ (NR; over RGB)",
    'clipiqa+_rn50_512' : "ClipIQA+ ResNet50 (NR; over RGB)",
    'clipiqa+_vitL14_512' : "ClipIQA+ ViT-L-14 (NR; over RGB)",
    'topiq_fr' : "TOPIQ (FR; over RGB)",
    'topiq_nr' : "TOPIQ (NR; over RGB)",
    'topiq_iaa' : "TOPIQ (NR Aesthetic; over RGB)",
    'topiq_fr-pipal' : "TOPIQ pretrained on PIPAL (FR; over RGB)",
    'topiq_nr-face' : "TOPIQ pretrained on FACE (NR; over RGB)",
    'topiq_nr-flive' : "TOPIQ pretrained on FLIVE (NR; over RGB)",
    'topiq_nr-spaq' : "TOPIQ pretrained on SPAQ (NR; over RGB)",
    'topiq_iaa_res50' : "TOPIQ pretrained on Res50 (NR Aesthetic; over RGB)",
    'stlpips-alex' : "ST-LPIPS (Alex) (FR; over RGB)",
    'stlpips-vgg' : "ST-LPIPS (VGG) (FR; over RGB)",
    'ilniqe' : "ILNIQE (NR; over RGB)",
    'musiq' : "MUSIQ (NR; over RGB)",
    'musiq-ava' : "MUSIQ pretrained on AVA (NR; over RGB)",
    'musiq-koniq' : "MUSIQ pretrained on KONIQ (NR; over RGB)",
    'musiq-paq2piq' : "MUSIQ pretrained on PaQ-2-PiQ (NR; over RGB)",
    'musiq-spaq' : "MUSIQ pretrained on SPAQ (NR; over RGB)",
    'tres' : "TRES (NR; over RGB)",
    'tres-flive' : "TRES pretrained on FLIVE (NR; over RGB)",
    'tres-koniq' : "TRES pretrained on KONIQ (NR; over RGB)",
    'liqe' : 'LIQE (NR; over RGB)',
    'liqe_mix' : 'LIQE MIX (NR; over RGB)',
    'q-align_iqa' : "Q-Align (Image; NR; over RGB)",
    'q-align_iaa' : "Q-Align (Image; NR Aesthetic; over RGB)",
    'q-align_vqa' : "Q-Align (Video; NR; over RGB)"
}
