class MetricsInfo():
    def __init__(self):
        self.vqmt_names = [
            'psnr',
            'identity',
            'ssim',
            'msssim',
            'msssim_fast',
            'msssim_precise',
            'msssim_cuda',
            '3ssim',
            '3ssim_cuda',
            'vqm',
            'blocking',
            'blurring',
            'blurring_delta',
            'msad',
            'mse',
            'niqe',
            'vmaf',
            'vmaf_legacy',
            'bfm',
            'bi_psnr',
            'ne',
            'psnr_Y'
        ]
        self.vqmt_types = {
            'psnr' : 'fr',
            'identity' : 'fr',
            'ssim' : 'fr',
            'msssim' : 'fr',
            'msssim_fast' : 'fr',
            'msssim_precise' : 'fr',
            'msssim_cuda' : 'fr',
            '3ssim' : 'fr',
            '3ssim_cuda' : 'fr',
            'vqm' : 'fr',
            'blocking' : 'nr',
            'blurring' : 'nr',
            'blurring_delta' : 'nr',
            'msad' : 'fr',
            'mse' : 'fr',
            'niqe' : 'nr',
            'vmaf' : 'fr',
            'vmaf_legacy' : 'fr',
            'bfm' : 'nr',
            'bi_psnr' : 'fr',
            'ne' : 'nr',
            'psnr_Y' : 'fr'
        }
        self.vqmt_metrics_vqmt_types = {
            'psnr' : 0,
            'identity' : 0,
            'ssim' : 0,
            'msssim' : 0,
            'msssim_fast' : 0,
            'msssim_precise' : 0,
            'msssim_cuda' : 2,
            'msssim OpenCL0' : 3,
            'msssim OpenCL1' : 3,
            '3ssim' : 2,
            '3ssim_cuda' : 2,
            '3ssim OpenCL0' : 4,
            '3ssim OpenCL1' : 4,
            'vqm' : 1,
            'blocking' : 6,
            'blurring' : 6,
            'blurring_delta' : 7,
            'msad' : 2,
            'mse' : 2,
            'niqe' : 6,
            'niqe OpenCL0' : 8,
            'vmaf' : 1,
            'vmaf OpenCL0' : 5,
            'vmaf OpenCL1' : 5,
            'vmaf_legacy' : 1,
            'vmaf_legacy OpenCL0' : 5,
            'vmaf_legacy OpenCL1' : 5,
            'bfm' : 6,
            'bi_psnr' : 1,
            'ne' : 6,
            'psnr_Y' : 9
        }
        self.vqmt_devices = {
            'msssim' : ['OpenCL0', 'OpenCL1'],
            '3ssim' : ['OpenCL0', 'OpenCL1'],
            'niqe' : ['OpenCL0'],
            'vmaf' : ['OpenCL0', 'OpenCL1'],
            'vmaf_legacy': ['OpenCL0', 'OpenCL1']
        }
        self.pyiqa_names = {
             'ahiq',
             'brisque',
             'clipiqa',
             'clipiqa+',
             'clipiqa+_rn50_512',
             'clipiqa+_vitL14_512',
             'cnniqa',
             'dbcnn',
             'fid',
             'fsim',
             'hyperiqa',
             'ilniqe',
             'laion_aes',
             'liqe',
             'liqe_mix',
             'maniqa',
             'musiq',
             'musiq-ava',
             'musiq-koniq',
             'musiq-paq2piq',
             'musiq-spaq',
             'paq2piq',
             'stlpips-alex',
             'stlpips-vgg',
             'topiq_fr',
             'topiq_fr-pipal',
             'topiq_iaa',
             'topiq_iaa_res50',
             'topiq_nr',
             'topiq_nr-face',
             'topiq_nr-flive',
             'topiq_nr-spaq',
             'tres',
             'tres-flive',
             'tres-koniq',
             'vif',
             'wadiqam_fr',
             'wadiqam_nr'   
        }
        self.pyiqa_types = {
             'ahiq' : 'fr',
             'brisque' : 'nr',
             'clipiqa' : 'nr',
             'clipiqa+' : 'nr',
             'clipiqa+_rn50_512' : 'nr',
             'clipiqa+_vitL14_512' : 'nr',
             'cnniqa' : 'nr',
             'dbcnn' : 'nr',
             'fsim' : 'fr',
             'hyperiqa' : 'nr',
             'ilniqe' : 'nr',
             'liqe' : 'nr',
             'liqe_mix' : 'nr',
             'maniqa' : 'nr',
             'musiq' : 'nr',
             'musiq-ava' : 'nr',
             'musiq-koniq' : 'nr',
             'musiq-paq2piq' : 'nr',
             'musiq-spaq' : 'nr',
             'paq2piq' : 'nr',
             'stlpips-alex' : 'fr',
             'stlpips-vgg' : 'fr',
             'topiq_fr' : 'fr',
             'topiq_fr-pipal' : 'fr',
             'topiq_iaa' : 'nr',
             'topiq_iaa_res50' : 'nr',
             'topiq_nr' : 'nr',
             'topiq_nr-face' : 'nr',
             'topiq_nr-flive' : 'nr',
             'topiq_nr-spaq' : 'nr',
             'tres' : 'nr',
             'tres-flive' : 'nr',
             'tres-koniq' : 'nr',
             'vif' : 'fr',
             'wadiqam_fr' : 'fr',
             'wadiqam_nr' : 'nr'   
        }
        self.qalign_types = {
             'q-align_iqa' : 'iqa',
             'q-align_iaa' : 'iaa',
             'q-align_vqa' : 'vqa'
        }
